### ISSUE TITLE
Migrate to new Azure subscription

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/testing-infrastructure#107] opened 2023-04-24 11:18 UTC
Once https://github.com/kedacore/governance/issues/31 completes, we need to migrate everything to our new Azure subscription with dedicated Azure AD instance.

**Comment by tomkerkhove** [comment] 2023-04-24 11:19
Once it is available, is this something you want to help on @JorTurFer?

**Comment by JorTurFer** [comment] 2023-04-24 13:36
I hope that just with a few clics in azure and some secrets updated, the whole infrastructure will be updated :) 🤞

**Comment by tomkerkhove** [comment] 2023-05-02 05:55
Subscription `afbc9e97-8dea-44a4-ad1c-ac577f221821` is live, maintainers were invited and should have contributor permissions to everything!

It turns out this is part of my Azure AD but I've granted permissions to manage AD apps as well.

**Comment by tomkerkhove** [comment] 2023-05-02 06:07
With regards to changing our automation - This is the never ending debate but are https://github.com/kedacore/testing-infrastructure/blob/main/.github/workflows/main.yaml#L24-L25 really secrets? We might want to move to the new YAML variables in GH Actions instead?

https://docs.github.com/en/actions/learn-github-actions/variables#defining-configuration-variables-for-multiple-workflows

**Comment by JorTurFer** [comment] 2023-05-02 06:24
Definitively, they can be variables. The problem is that the secrets for the storage account still are secrets, so I'd keep all together. Maybe we can use the federated login for that part too, making the things easier.
In any case, I prefer to keep the workflow as it is (using `pull_request_target`) because otherwise, with the automatic execution, someone can deploy/remove infrastructure on PR

**Comment by JorTurFer** [comment] 2023-05-03 22:46
All the resources have been created in the new subscription and all the variables have been updated. We need to check that everything is working, but I'd say that we have moved our infra

**Comment by JorTurFer** [comment] 2023-07-09 14:30
I close this because we have migrated and we have been using the new infra for 2 months

**Closed by JorTurFer** 2023-07-09 14:30 UTC
